In [42]:
import numpy as np
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# [Problem 1] Matrix product is calculated manually 
[Na, Ma] = A.shape
[Nb, Mb] = B.shape

# Matrix A and Matrix B can be multiplicable if the columns of A equal to the rows of B.
# If this condition is satisfied then the resultant matrix C will have the size rows of A times columns of B
# C[i][j] = Summation (from k=0 to Nb) A[i][k]*B[k][j]

if (Ma != Nb):
   print("Multiplication is not possible")
C = np.zeros((Na,Mb))
print(C)
for i in range(0,Na,1):
    for j in range(0,Mb,1):
             for k in range(0,Ma,1):
                 C[i][j] = C[i][j]+ A[i][k]*B[k][j]
print(C)               

# [Problem 2] Calculation by NumPy function
C2 = np.matmul(A,B)
print(C2)
C2dot = np.dot(A,B)
print(C2dot)

# [Problem 3] Implementation of calculation of a certain element
[Na, Ma] = A.shape
[Nb, Mb] = B.shape
if (Ma != Nb):
   print("Multiplication is not possible")
   Message = "Multiplication is not possible"
C = np.zeros((Na,Mb))
print(C)
for i in range(0,Na,1):
    for j in range(0,Mb,1):
             for k in range(0,Ma,1):
                 C[i][j] = C[i][j]+ A[i][k]*B[k][j]
print(C)               
# [Problem 4] Creating a function that performs matrix multiplication

def Multiply(A,B):
    [Na, Ma] = A.shape
    [Nb, Mb] = B.shape
    C = np.zeros((Na,Mb))
    if (Ma != Nb):
       print("Multiplication is not possible")
       Message = "Multiplication is not possible"
       return(C, Message)
    Message = "Multiplication is possible"
    for i in range(0,Na,1):
        for j in range(0,Mb,1):
            for k in range(0,Ma,1):
                C[i][j] = C[i][j]+ A[i][k]*B[k][j]
    return(C, Message)
C, Message = Multiply(A,B)

# [Problem 5] Judge the input whose calculation is not defined
D = np.array([[-1, 2, 3], [4, -5, 6]])
E = np.array([[-9, 8, 7], [6, -5, 4]])
C, Message = Multiply(D,E)

# [Problem 6] Transposition
print(A)
print(np.transpose(A))
print(A.T)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
Multiplication is not possible
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[-1  4  7]
 [ 2 -5  8]
 [ 3  6 -9]]
[[-1  4  7]
 [ 2 -5  8]
 [ 3  6 -9]]
